var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var k=0;return function(){return k<f.length?{done:!1,value:f[k++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var k="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return k?k.call(f):$jscomp.arrayIterator(f)};
(function(f){var k=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};String.prototype.trim||function(){String.prototype.trim=function(){return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")}}();var p=function(a){a=parseInt(a.toString(),10).toString(16);1==a.length&&(a="0".concat(a));return a},x=function(){for(var a=[],b=15;0<=b;b--){var c=b.toString(16);1==c.length&&(c=c.concat(c));a[15-b]="#".concat(c,
    c,c)}return a},q=function(a,b,c){0>c&&(c+=1);1<c&&--c;return 1>6*c?a+(b-a)*c*6:1>2*c?b:2>3*c?a+(b-a)*(2/3-c)*6:a},y=function(){for(var a=[],b=0;360>b;b++){var c=b/360;var e=q(0,1,c+1/3);var g=q(0,1,c);c=q(0,1,c-1/3);g=[255*e,255*g,255*c];a[b]="#".concat(p(g[0]),p(g[1]),p(g[2]))}return a};$(f).ready(function(){var a=function(){setTimeout(function(){$.get("/ping.php?uniq="+k(),function(b){a()})},6E4)};a()});$("#upload-image-btn").click(function(){window.open("/uploader/")});$(f).ready(function(){-1!==
location.href.indexOf("/tracker")&&$("iframe").add("img").each(function(a,b){$(b).children().each(function(b,a){a=$(a);800<a.position().top&&a.remove()})})});$(f).ready(function(){if(-1!==location.href.indexOf("/topic")){var a=function(){var b=location.href.indexOf("#");-1!==b&&(b=location.href.substr(b+1),b.length&&(b=parseInt(b,10),$("html, body").animate({scrollTop:$("#message"+b).position().top},"fast")))};a();window.addEventListener("hashchange",function(b){a()});$(".triangle-up").click(function(){var b=
    $(this);if(!b.hasClass("triangle-up-disabled")){var a=parseInt(b.attr("data-id"),10),e=b.attr("data-userid");(function(b){$.get("/vote.php?id="+a+"&userid="+e+"&value=1",function(a){!0===a.answer?(b.addClass("triangle-up-disabled"),b.parent().find(".triangle-down").addClass("triangle-down-disabled"),b.parent().find(".likes-counter").text(a.count)):console.log("Voting error: "+a.reason)})})(b)}});$(".triangle-down").click(function(){var b=$(this);if(!b.hasClass("triangle-down-disabled")){var a=parseInt(b.attr("data-id"),
    10),e=b.attr("data-userid");(function(b){$.get("/vote.php?id="+a+"&userid="+e+"&value=-1",function(a){!0===a.answer?(b.addClass("triangle-down-disabled"),b.parent().find(".triangle-up").addClass("triangle-up-disabled"),b.parent().find(".likes-counter").text(a.count)):console.log("Voting error: "+a.reason)})})(b)}});$("#preview-btn").click(function(){var b=$("form");b.attr("action","/preview/");b.submit()});$("img").each(function(b,a){a=$(a);if(-1!==a.attr("src").indexOf("gravatar")){var c=$(a.parent().find("a")[0]);
    a.css("left",c.position().left+c.width()-45+"px")}})}});$(f).ready(function(){-1!==location.href.indexOf("/preview/")&&($("#preview-btn").click(function(){var a=$("form");a.attr("action","/preview/");a.submit()}),$("#cancel-btn").click(function(){location.href="/topic/"+$("input[name=topicid]").val()+"/"}))});$(f).ready(function(){-1!==location.href.indexOf("/profile/")&&$("#smiles").change(function(){$.get("/switchsmiles.php?value="+(this.checked?"checked":"unchecked"))})});$(f).ready(function(){if(-1!==
    location.href.indexOf("/uploader/")){var a=$("input[type=file]")[0],b=$(a),c=b.val().replace(/\\/g,"/").replace(/.*\//,"");b.trigger("fileselect",[c]);$(".btn-file :file").on("fileselect",function(b,c){var e=$(a).parents(".input-group").find(":text");e.length?e.val(c):c&&alert(c)});var e=function(a){if(a.files&&a.files[0]){var b=new FileReader;b.onload=function(a){$("#img-upload").css("background-image",'url("'+a.target.result+'")')};b.readAsDataURL(a.files[0])}};$("#imgInp").change(function(){e(a)})}});
    $(f).ready(function(){-1!==location.href.indexOf("/messages/")&&$("input[type=button].btn-primary").each(function(a,b){b=$(b);(function(a,b){a.click(function(){location.href="/sendmessage/"+b+"/"})})(b,b.attr("data-id"))});-1!==location.href.indexOf("/messages/")&&$("input[type=button].btn-danger").each(function(a,b){})});$(f).ready(function(){$("#btn-search").click(function(){$(this).parent().parent().find("form").submit()})});$(f).ready(function(){$(f).ready(function(){$("#submit-button").click(function(){$("#pass1").val()==
    $("#pass2").val()&&$("form").submit()})})});$(f).ready(function(){$("pre code").each(function(a,b){hljs.highlightBlock(b)})});var l,d,m=function(){console.log("Unsupported browser version!")},v=function(a){var b=d.selectionStart;d.value=d.value.substr(0,b)+a+d.value.substr(b,d.value.length-b);d.selectionEnd=d.selectionStart=b+a.length;d.focus()},r=function(a,b){var c=d.selectionStart,e=d.selectionEnd;if(0<e-c){var g=d.value.substr(c,e-c);c=d.value.substr(0,c)+a+g+b;d.value=c+d.value.substr(e,d.value.length-
        e)}else e=d.selectionStart,c=d.value.substr(0,e)+a,d.value=c+b+d.value.substr(e,d.value.length-e);d.selectionEnd=d.selectionStart=c.length;d.focus()},n=function(a){var b=f.createElement("a");1==l?b.style.cursor="pointer":b.href="javascript:void(0);";b.innerHTML=a;return b},z=function(a,b,c){b=n('<img src="'+b+'" alt="'+c+'" />');b.addEventListener("click",function(){v(c)},!1);a.appendChild(b)},w=function(a,b){sizer="&nbsp;";var c=n('<span style="background-color:'+b+';">'+sizer+"</span>");c.addEventListener("click",
        function(){r("[color="+b+"]","[/color]")},!1);a.appendChild(c)},t=function(a,b,c){var e=f.createElement("span");e.appendChild(b);e.innerHTML=e.innerHTML;e.addEventListener("click",c,!1);a.appendChild(e)},A=function(a){var b=f.createElement("span");b.innerHTML="&nbsp;&nbsp;&nbsp;";a.appendChild(b)},B=function(a,b){var c=[],e=0,g;for(g in a)e++,e>=b&&(c.push(a[g]),e=0);return c},C=function(a){console.log("create tags");var b=[["https://russiancoders.club/static/bold.png","\u0416\u0438\u0440\u043d\u044b\u0439 \u0448\u0440\u0438\u0444\u0442",
            "[b]","[/b]"],["https://russiancoders.club/static/strike.png","\u041f\u0435\u0440\u0435\u0447\u0451\u0440\u043a\u043d\u0443\u0442\u044b\u0439 \u0448\u0440\u0438\u0444\u0442","[s]","[/s]"],["https://russiancoders.club/static/italic.png","\u041d\u0430\u043a\u043b\u043e\u043d\u043d\u044b\u0439 \u0448\u0440\u0438\u0444\u0442","[i]","[/i]"],["https://russiancoders.club/static/underline.png","\u041f\u043e\u0434\u0447\u0451\u0440\u043a\u043d\u0443\u0442\u044b\u0439 \u0448\u0440\u0438\u0444\u0442","[u]","[/u]"],
            [],["https://russiancoders.club/static/h1.png","H1","[h1]","[/h1]"],["https://russiancoders.club/static/h2.png","H2","[h2]","[/h2]"],["https://russiancoders.club/static/h3.png","H3","[h3]","[/h3]"],["https://russiancoders.club/static/h4.png","H4","[h4]","[/h4]"],[],["https://russiancoders.club/static/strong.png","strong","[strong]","[/strong]"],["https://russiancoders.club/static/small.png","small","[small]","[/small]"],["https://russiancoders.club/static/sup.png","\u0412\u0435\u0440\u0445\u043d\u0438\u0439 \u0438\u043d\u0434\u0435\u043a\u0441",
                "[sup]","[/sup]"],["https://russiancoders.club/static/sub.png","\u041d\u0438\u0436\u043d\u0438\u0439 \u0438\u043d\u0434\u0435\u043a\u0441","[sub]","[/sub]"],["https://russiancoders.club/static/pre.png","\u041e\u0442\u0444\u043e\u0440\u043c\u0430\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442","[pre]","[/pre]"],["https://russiancoders.club/static/hr.png","\u0420\u0430\u0437\u0434\u0435\u043b\u0438\u0442\u0435\u043b\u044c","[hr]"],["https://russiancoders.club/static/p.png",
                "\u041f\u0430\u0440\u0430\u0433\u0440\u0430\u0444","[p]","[/p]"],["https://russiancoders.club/static/br.png","\u041f\u0435\u0440\u0435\u043d\u043e\u0441 \u0441\u0442\u0440\u043e\u043a\u0438","[br]"],[],["https://russiancoders.club/static/youtube.png","YouTube","[youtube=","]"],["https://russiancoders.club/static/img.png","\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435","[img=","]"],["https://russiancoders.club/static/url.png","\u0421\u0441\u044b\u043b\u043a\u0430","[url=","]","[/url]"]],
        c,e;for(e in b)(function(b){5==b.length?(c=n('<img src="'+b[0]+'" alt="'+b[1]+'">'),function(b){t(a,c,function(){var a=b[2],c=b[3],e=b[4],g=d.selectionStart,f=d.selectionEnd;if(0<f-g){var u=d.value.substr(g,f-g);a=d.value.substr(0,g)+a+u+c+u+e;d.value=a+d.value.substr(f,d.value.length-f);d.selectionEnd=d.selectionStart=a.length;d.focus()}else r(a,c+e)})}(b)):4==b.length?(c=n('<img src="'+b[0]+'" alt="'+b[1]+'">'),function(b){t(a,c,function(){r(b[2],b[3])})}(b)):3==b.length?(c=n('<img src="'+b[0]+
        '" alt="'+b[1]+'">'),function(b){t(a,c,function(){v(b[2])})}(b)):0==b.length&&A(a)})(b[e]);b=f.createElement("br");a.appendChild(b);b=B(y(),2);for(e in b)w(a,b[e]);b=x();for(e in b)w(a,b[e]);var g=[["https://russiancoders.club/static/smile.gif",":-)"],["https://russiancoders.club/static/wink.gif",";-)"],["https://russiancoders.club/static/tongue.gif",":-P"],["https://russiancoders.club/static/sorrow.gif",":-("],["https://russiancoders.club/static/cry.gif",":'-("],["https://russiancoders.club/static/amazement.gif",
        "O_O"],["https://russiancoders.club/static/laugh.gif",":-D"],["https://russiancoders.club/static/rofl.gif","[rofl]"],["https://russiancoders.club/static/crazy.gif","O_o"],["https://russiancoders.club/static/good.gif","[good]"],["https://russiancoders.club/static/scratch.gif","[scratch]"],["https://russiancoders.club/static/rtfm.gif","[rtfm]"],["https://russiancoders.club/static/stop.gif","[stop]"],["https://russiancoders.club/static/umnik.gif","[genius]"],["https://russiancoders.club/static/angel.gif","[angel]"],["https://russiancoders.club/static/love.gif",
        "[love]"],["https://russiancoders.club/static/idea.gif","[idea]"],["https://russiancoders.club/static/kill.gif","[kill]"],["https://russiancoders.club/static/bad.gif","[bad]"],["https://russiancoders.club/static/smoke.gif","[smoke]"],["https://russiancoders.club/static/angry.gif","[angry]"],["https://russiancoders.club/static/devil.gif","[devil]"],["https://russiancoders.club/static/bomb.gif","[bomb]"],["https://russiancoders.club/static/yahoo.gif","[yahoo]"],["https://russiancoders.club/static/dance.gif","[dance]"],
        ["https://russiancoders.club/static/wall.gif","[wall]"],["https://russiancoders.club/static/sex.gif","[sex]"]];b=f.createElement("br");a.appendChild(b);for(e in g)z(a,g[e][0],g[e][1])};$(f).ready(function(){$("#not-robot").change(function(){$(this).is(":checked")?($("#main-form").attr("action","/doregister.php"),$("#submit-button").attr("disabled",!1)):$(this).prop("checked",!0)})});(function(){$(".tracker-gradient").length&&$(".tracker-gradient").each(function(a,b){var c=$(b);800>=c.parent().find(".row").height()&&
    c.remove()})})();$(function(){$(".left-navigation-header").click(function(){(function(a){var b=$(".left-navigation-header").length-1,c=a.attr("id");$(".left-navigation-header").each(function(e,g){$(g).attr("id")!=c&&$(g).parent().find("ul").slideUp("fast",function(){--b||a.parent().find("ul").slideDown()})})})($(this));return!0})});$(function(){if(800>$(window).width()){var a=$(window).width()/800;console.log("zoom: "+a);$("body").css("zoom",$(window).width()/800).css("-moz-transform","scale("+a+
        ")").css("-moz-transform-origin","0 0")}});$(function(){$(".cute-post").each(function(a,b){(function(b){b.click(function(){var a=b.parent().parent().parent().parent().find(".panel-body").find(".col-md-12"),c=window.getSelection(),d=$(c.baseNode).parent();c=a[0]==d[0]?(c+"").trim():a.text().trim();c=a=c.split("\r\n");a=[];var h=$jscomp.makeIterator(c);for(d=h.next();!d.done;d=h.next())for(c=d.value.split("\r"),d=$jscomp.makeIterator(c),c=d.next();!c.done;c=d.next())a.push(c.value.trim());c=a;a=[];
        h=$jscomp.makeIterator(c);for(d=h.next();!d.done;d=h.next())for(c=d.value.split("\n"),d=$jscomp.makeIterator(c),c=d.next();!c.done;c=d.next())a.push(c.value.trim());c=a;a=[];h=$jscomp.makeIterator(c);for(d=h.next();!d.done;d=h.next())for(c=d.value.split("<br>"),d=$jscomp.makeIterator(c),c=d.next();!c.done;c=d.next())a.push(c.value.trim());c="";a=$jscomp.makeIterator(a);for(d=a.next();!d.done;d=a.next())c+="> "+d.value+"\r\n";d=b.parent().parent().parent().parent().find(".panel-heading").find(".col-md-8").find("a").first();
        a=b.parent().parent().parent().parent().find(".panel-heading").find(".col-md-8").find("a").last();d=d.attr("href");a=a.text();a="[url="+d+"][b]"+a+"[/b][/url]\r\n"+c;$("textarea").text(a);$([f.documentElement,f.body]).animate({scrollTop:$("textarea").offset().top},2E3);return!1})})($(b))})});(function(){if(-1!=f.location.href.indexOf("/topic/")||-1!=f.location.href.indexOf("/preview/")||-1!=f.location.href.indexOf("/sendmessage/")||-1!=f.location.href.indexOf("/createtopic")){var a=window.navigator.userAgent;
        if(-1==a.indexOf("Opera")&&-1==a.indexOf("Firefox")&&-1==a.indexOf("Chrome"))m();else{l=-1!=a.indexOf("Opera")?1:-1!=a.indexOf("Firefox")?2:3;if(1==l){a=/Opera\/(\d+).(\d+)/;var b=a.exec(window.navigator.userAgent);a=b[1];b=b[2];if(9>a){m();return}if(9==a&&5>b){m();return}}else if(2==l||3==l){if(2==l&&(a=/Firefox\/(\d+).(\d+)/,b=a.exec(window.navigator.userAgent),a=b[1],3>a)){m();return}}else{m();return}a=f.getElementsByTagName("textarea");0<a.length&&(d=a[0],a=f.createElement("div"),C(a),d.parentNode.insertBefore(a,
            d))}}})()})(document); 
